apiVersion: v1
data:
  better_secret: ?{base64:eyJkYXRhIjogIlpHMUdjVXhZYUZOV2JUVXpWa1ZrZFU1NlVsVmhXRmsxV1RGdk5GUXlPVlpqV0VGMFVWVnNjVlV3TlVWUlZ6bHpaR3RXVjA1SFdsQmhkejA5IiwgImVuY29kaW5nIjogImJhc2U2NCIsICJ0eXBlIjogImJhc2U2NCJ9:embedded}
  encoded_secret: bXlfc2VjcmV0
kind: Secret
metadata:
  labels:
    name: echo-server
  name: echo-server
type: Opaque
